# config.yml
local_backend: true

# live
backend:
  name: git-gateway
  # branch: main # Branch to update (optional; defaults to master)
  branch: dev # Branch to update. Dev is now selected so we dont override any content that the program is adding.

media_folder: '_uploads'
public_folder: '/uploads' # The src attribute for uploaded media will begin with /images/uploads
# publish_mode: 'editorial_workflow'
display_url: 'https://indianstates.csis.org'
logo_url: 'https://raw.githubusercontent.com/CSIS-iLab/energy-database/main/public/android-chrome-192x192.png'
collections:
  - name: 'analysis'
    label: 'Analyses'
    label_singular: 'Analysis'
    folder: '_analysis/'
    create: true
    editor:
      preview: false
    # slug: '{{slug}}'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    sortable_fields: ['title', 'date', 'author', 'states']
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Breadcrumbs', name: 'breadcrumbs', widget: 'hidden', default: 'analysis' }
      - { label: 'Is analysis', name: 'is_analysis', widget: 'hidden', default: true }
      - { label: 'Content Type', name: 'content_type', widget: 'hidden', default: 'analysis' }
      # - { label: 'Post Type', name: 'post_type', widget: 'relation', collection: 'post_types',
      #     display_fields: [title],
      #     search_fields: [title],
      #     value_field: 'title'
      #   }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', time_format: false }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false, collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' }}
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'States', name: 'states', widget: 'relation', collection: 'states', multiple: true,
          display_fields: [title],
          search_fields: [title],
          value_field: 'title',
          required: false
        }
      - { label: 'Sectors', name: 'sectors', widget: 'relation', collection: 'sectors', multiple: true, display_fields: [title], search_fields: [title], value_field: 'title', required: false  }
      - { label: 'Sub Sectors', name: 'subsectors', widget: 'relation', collection: 'subsectors', multiple: true, display_fields: [title], search_fields: [title], value_field: 'title', required: false }
      - { label: 'Is Featured?', name: 'is_featured', widget: 'boolean', default: false, required: false }
      - { label: 'Featured Image', name: 'feature_image', widget: 'image', choose_url: false, required: false }
      - { label: 'Featured image credit', name: 'feature_image_credit', widget: 'text', required: false }
      - label: 'Sources'
        label_singular: 'Source'
        name: 'sources'
        widget: 'list'
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
        required: false  
      - label: 'Details'
        label_singular: 'Detail'
        name: 'details'
        widget: 'list'
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
        required: false
      - { label: 'Author', name: 'author', widget: 'relation', collection: 'authors', multiple: true, display_fields: [name], search_fields: [name], value_field: 'name', }
      - { label: 'PDF', name: 'pdf', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'articles'
    label: 'Articles'
    label_singular: 'Article'
    folder: '_posts/'
    create: true
    editor:
      preview: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    sortable_fields: ['title', 'date', 'author', 'states']
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Content Type', name: 'content_type', widget: 'hidden', default: 'articles' }
      - { label: 'Breadcrumbs', name: 'breadcrumbs', widget: 'hidden', default: 'articles' }
      - { label: 'Is analysis', name: 'is_analysis', widget: 'hidden', default: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', time_format: false }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false, collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' }}
      - { label: 'States', name: 'states', widget: 'relation', collection: 'states', multiple: true,
          display_fields: [title],
          search_fields: [title],
          value_field: 'title',
          required: false
        }
      - { label: 'Sectors', name: 'sectors', widget: 'relation', collection: 'sectors', multiple: true,
          display_fields: [title],
          search_fields: [title],
          value_field: 'title',
          required: false
        }
      - { label: 'Subsectors', name: 'subsectors', widget: 'relation', collection: 'subsectors', multiple: true,
          display_fields: [title],
          search_fields: [title],
          value_field: 'title',
          required: false
        }
      - label: 'Sources'
        label_singular: 'Source'
        name: 'sources'
        widget: 'list'
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
        required: false  
      - label: 'Details'
        label_singular: 'Detail'
        name: 'details'
        widget: 'list'
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
        required: false
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }

  - name: 'authors'
    label: 'Authors'
    label_singular: 'Author'
    folder: '_authors/'
    create: true
    editor:
      preview: false
    identifier_field: name
    slug: '{{slug}}'
    sortable_fields: ['name', 'position']
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      # - { label: 'Display Name', name: 'display_name', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image', choose_url: false, required: false }
      - { label: 'Current Staff', name: 'current_staff', widget: 'boolean', default: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'national-goals'
    label: 'National Goals'
    label_singular: 'National Goal'
    folder: '_national-goals/'
    create: true
    slug: '{{slug}}'
    sortable_fields: ['title', 'tags', 'last_updated_at']
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'national-goals' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false, collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' }}
      - { label: 'Sectors', name: 'sectors', widget: 'relation', collection: 'sectors', multiple: true,
          display_fields: [title],
          search_fields: [title],
          value_field: 'title',
          required: false
        }
      - { label: 'Subsectors', name: 'subsectors', widget: 'relation', collection: 'subsectors', multiple: true,
          display_fields: [title],
          search_fields: [title],
          value_field: 'title',
          required: false
        }
      - { label: 'Data source', name: 'data_source', widget: 'hidden',  default: '{{replace-this-with-data-name}}'}
      - { label: 'Data Label', name: 'data_label', widget: 'string', hint: 'The appropriate label for the type of data youâ€™re tracking (MW, %, KM, etc.)' }
      - { label: 'Data Missing Message', name: 'data_missing_message', widget: 'string' }
      - { label: 'Show Map?', name: 'show_map', widget: 'boolean', hint: 'If you want to display the map section of the tracker page'}
      - label: 'Map'
        name: 'map'
        widget: 'object'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Legend Title', name: 'legend_title', widget: 'string' }
          - { label: 'Value Suffix', name: 'value_suffix', widget: 'string' }
      - { label: 'Show Progressbars?', name: 'show_progressbars', widget: 'boolean', hint: 'If you want to display the progress bars section of the tracker page'}
      - label: 'Progress Bars'
        name: 'progressbars'
        widget: 'object'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'State Text', name: 'state_text', widget: 'string', hint: 'The text that appears on the state pages in the "related national goals" box.' }
      - { label: 'Last Updated', name: 'last_updated_at', widget: 'datetime', time_format: false }
      - label: 'Sources'
        label_singular: 'Source'
        name: 'sources'
        widget: 'list'
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
        required: false  
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'resources'
    label: 'Resources'
    label_singular: 'Resource'
    folder: '_resources/'
    create: true
    # slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    slug: '{{slug}}'
    sortable_fields: ['title', 'type', 'author', 'posted_on']
    editor:
      preview: false
    fields:
      - { label: 'Content Type', name: 'content_type', widget: 'hidden', default: 'resource' }
      - { label: 'Type', name: 'type', widget: 'select', allow_add: false,
          options: [
            'Archives',
            'Electricity',
            'Electric Mobility',
            'Energy Transition',
            'Health',
            'State Clean Energy Goal Tracker',
            'Technology'
          ],
          default: ['Archives']
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Link', name: 'link', widget: 'string', hint: 'https://example.com' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'text' }
      - { label: 'Publish Date', name: 'posted_on', widget: 'datetime', date_format: 'MM.YYYY', time_format: false, format: 'LLL' }
      - { label: 'Sectors', name: 'sectors', widget: 'relation', collection: 'sectors', multiple: true,
          display_fields: [title],
          search_fields: [title],
          value_field: 'title'
        }
      - { label: 'Subsectors', name: 'subsectors', widget: 'relation', collection: 'subsectors', multiple: true,
          display_fields: [title],
          search_fields: [title],
          value_field: 'title',
        }

  - name: 'post_types'
    label: 'Post types'
    label_singular: 'Post type'
    folder: '_post-types/'
    create: true
    # slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Featured Image', name: 'feature_image', widget: 'image', choose_url: false, required: false }
      - { label: 'Featured image credit', name: 'feature_image_credit', widget: 'text' }

  - name: 'sectors'
    label: 'Sectors'
    label_singular: 'Sector'
    folder: '_sectors/'
    create: true
    slug: '{{slug}}'
    sortable_fields: ['title']
    editor:
      preview: false
    fields:
      - { label: 'Content Type', name: 'content_type', widget: 'hidden', default: 'sector' }
      - { label: 'Breadcrumbs', name: 'breadcrumbs', widget: 'hidden', default: 'sectors' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'feature_image', widget: 'image', choose_url: false, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'subsectors'
    label: 'Sub Sectors'
    label_singular: 'Sub Sector'
    folder: '_subsectors'
    create: true
    slug: '{{slug}}'
    sortable_fields: ['title', 'sectors']
    editor:
      preview: false
    fields:
      - { label: 'Content Type', name: 'content_type', widget: 'hidden', default: 'subsector' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Sectors', name: 'sector', widget: 'relation', collection: 'sectors', display_fields: ['title'], search_fields: ['title'], value_field: 'title' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'states'
    label: 'States'
    label_singular: 'State'
    folder: '_states'
    create: true
    slug: '{{slug}}'
    sortable_fields: ['title', 'size', 'population']
    editor:
      preview: false
    fields:
      - { label: 'Content Type', name: 'content_type', widget: 'hidden', default: 'state' }
      - { label: 'Breadcrumbs', name: 'breadcrumbs', widget: 'hidden', default: 'states' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Featured Images'
        name: 'feature_images'
        widget: 'object'
        fields:
          - label: 'Primary'
            name: 'primary'
            widget: 'object'
            fields:
              - { label: 'Image', name: 'image', widget: 'image', choose_url: false, required: false }
              - { label: 'Credit', name: 'credit', widget: 'string' }
          - label: 'Secondary'
            name: 'secondary'
            widget: 'object'
            fields:
              - { label: 'Image', name: 'image', widget: 'image', choose_url: false, required: false }
              - { label: 'Credit', name: 'credit', widget: 'string' }
      - { label: 'Size', name: 'size', widget: 'string' }
      - { label: 'Population', name: 'population', widget: 'string' }
      - { label: 'Party affiliation', name: 'party_affiliation', widget: 'string' }
      - { label: 'Legislative seats', name: 'legislative_seats', widget: 'string' }
      - { label: 'Rajya seats', name: 'rajya_seats', widget: 'string' }
      - { label: 'Lok_seats', name: 'lok_seats', widget: 'string' }
      - { label: 'GDP', name: 'gdp', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'trackers'
    label: 'Trackers'
    label_singular: 'Tracker'
    extension: json
    format: json
    create: false
    editor:
      preview: false
    files:      
      - label: 'Solar Tracker'
        name: 'solar-tracker'
        file: '_data/national-goals/solar-performance-tracker.json'
        fields:
          - label: 'States'
            name: 'tracker'
            widget: 'list'
            allow_add: false
            collapsed: true
            fields:
              - { name: 'state' }
              - { name: 'national_contribution' }
              - { name: 'state_target' }
              - { name: 'state_achieved' }
              - { name: 'state_percentage' }
                    
      - label: 'Wind Tracker'
        name: 'wind-tracker'
        file: '_data/national-goals/wind-performance-tracker.json'
        fields:
          - label: 'States'
            name: 'tracker'
            widget: 'list'
            allow_add: false
            collapsed: true
            fields:
              - { name: 'state' }
              - { name: 'national_contribution' }
              - { name: 'state_target' }
              - { name: 'state_achieved' }
              - { name: 'state_percentage' }
